
#pragma once

#define MASTER_LEFT

#define USE_SERIAL_PD2

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 200

#define LEADER_TIMEOUT 300
#define LEADER_PER_KEY_TIMING

#define COMBO_COUNT 1
